version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: gene_explorer_api
    expose:
      - "8000"
    environment:
      - GUNICORN_CMD_ARGS=--timeout 120
    restart: unless-stopped

  web:
    image: nginx:alpine
    container_name: gene_explorer_web
    ports:
      - "8080:80"
    depends_on:
      - api
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

